<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/register.css"> 
    <title>Registro</title>
</head>
    <body>
        <?php if (isset($errorMessage)): ?>
            <div class='alert alert-danger' role='alert'>
                <?= htmlspecialchars($errorMessage) ?>
            </div>
        <?php endif; ?>

        <div class="login-container">
            <form action="registerUser" method="POST" class="login-form">
                <h2 class="form-title">Registrarse</h2>

                <div class='form-group'>
                    <label for='email'>Correo electrónico</label>
                    <input type='email' class='form-control' id='email' name='email' placeholder="Introduce tu correo" required>
                </div>

                <div class='form-group'>
                    <label for='password'>Contraseña</label>
                    <input type='password' class='form-control' id='password' name='password' placeholder="Introduce tu contraseña" required>
                </div>

                <button type='submit' class='btn btn-primary'>Registrarse</button>
                <div class="form-footer">
                    <p>¿Ya tienes una cuenta? <a href="login">Inicia sesión</a></p>
                </div>
            </form>
        </div>
    </body>
</html>